export ALLOW_MISSING_DEPENDENCIES=true
export FOX_BUILD_DEVICE=NpadAir
export LC_ALL="C"
export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
export FOX_VANILLA_BUILD=1
export FOX_AB_DEVICE=1
export OF_FORCE_PREBUILT_KERNEL=1
export OF_ALLOW_DISABLE_NAVBAR=0
